[gspread]
gsheet_key = "1dSLBX28xN5yJe48OIviUy6FgzM96P17AW4LM0Ow03eg"
type = "service_account"
project_id = "experiment-458407"
private_key_id = "09ac471725d28d836e52adbd4cb6d0e1e8070de8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDTKE2rjxOLcRwo
OPm/E8cVAMxp7UUsywfsOXF2uFnKiRtPaPgYAhTkMyzI3UQp1Q3EQr6UWqxbY73b
GADcLPjtVWqyl8SNY1v1Rc6OuUnGMJ9pwzzO+PfwZMgSM/l5+YLmgieDqMPNrcfS
+t6HdbTywtHxiHOP7bunDnvG0/83LQnFkcwXZHzXx8alm9VO+KBk8wwcdB4A2x9H
K6Ve/0bCL2viz3BoSrVOYWXtcpkdpMlvDZk7Cd6cMDBJpu7MvYZYflF5Lkbr+TdO
BhEk5H2+bSz9kM9oevm/uFOAgeDuA3Lf9c9iddpaH08ayU8xKfG58OLT/hqxepn9
zxUuK2WrAgMBAAECggEAAdCfKxU6cOCvgivL/1e/Rpxwciaib61tEeg3Slk9frxD
JyF68TkVweJfHt9CZm0/RlhGhN+317wM1gHBgolc0floE3hMR0s7CQNcSgv1daxV
6m+A3P/B1DShjZqAKSUhk80H/VDP7tTw2nNI9cQavCcIulLW0qSTkAhTvKFDPwLY
ylIMoRRdEH1sHprc8EFbMYBoG95B4DplwTvQxTJYuI6hQ/bnt5VsLcRY0QmI+CqT
zMMdpdEhHZIOmoKzGytIeV23mREOwi4s4cANbJc/aDRhHdU5GZ3FqVEJfycVtlUd
SeOe1gfUOzYzg7KRUI0r9YlHaHgJCQDQPsyh1eHZkQKBgQDyL1kQ0aXKZWraUg4t
z7CmD7S6qJnWSZ6yEu9Jyy9P/UJX4uauTIkY1XeVGFcnuF3yoYOscdGHvigHsD3Z
Uh3psQBBgUsH8GzIC3s6c4iBuvEkRxqtgD4KIhXl1GX9/NVnm1Qd1kV++oIFY5Bo
4HOCF8E+uBUAJMgN8o8o/rpwEQKBgQDfM9t/iurxI3lSqNGfWpu2rq6clkVgoIZg
MTRP2L87TQPhyKjebTlJ8j5mLT/6mRCAHlXiXSilQzVMeKRiTDo/JgT2wLxgu2iA
7VCK3lGUAiCWC7N4X7q98qpgIkc2gqRU48fysdWeHagjRMAwM9w+I4JspIDBus2z
toCTvWw1+wKBgHhYGtQGuXGnj79JAw60o70BFPekDD21e4xVaF6s/qeq26q8b5Cx
K3cRrEiEPdrY/KYyqDGqpUnkrhOT+kfhTEfx0oS6cMRTLlsBiYx0GKMOeAFk69bH
YQy7/1Gjh8L8PjcrslLZRNNiO/Xdkcbrsbo1f6tg4d6eaGK143mlipNhAoGADMuf
QK+JCmvbL6bn5Xe/R3i6H9XpgkGRkoAfnJgzVkXy/AWR0LZ4O0n808SyTz5pGL8k
c0ad5uN0cb7UxaHTEP2v+SlRY0Y7FnEEVgGqsY5xqchf8H2kafE4XSx54qEYpJku
RDZ3pYnTsrnlPp4qeRF2D55al0CLPEsxEcchJfMCgYBHxb7sm7REPuQAtQ3Z0zuZ
w/Ti6AWzZ75m6fV3jYZxZq/FmCbC5hBvTMkpxtzHpawit3LxmIu1H2JcnZS9Q5lb
LkgIL0qdd/IO0W9UhLvoDPREmR/uMeOqJMo2/FwqTG0ufaVtpuEhmH2MX6jP8fhJ
g+2SvzZBnhQPrVhzzBDgxQ==
-----END PRIVATE KEY-----"""
client_email = "experiment@experiment-458407.iam.gserviceaccount.com"
client_id = "106270045629595529441"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/experiment%40experiment-458407.iam.gserviceaccount.com"
